### PR TITLE
Feature/pyscript

### LINKED ISSUE #9: Python script for generating the booklets

### PR DESCRIPTION
**Pull request by PietroPrandini**
Closes #9

### CODE REVIEW

**Comment by maccacaromichele** [comment]
Is it possible to download the chants (lyrics and music)?

**Comment by maccacaromichele** [comment]
I've downloaded the book! Although I've not had the chance to use it yet, I find it very well done and very useful! Keep up the good job

**Comment by BeyondType1Michael** [comment]
I've downloaded the book and I've found it really useful! Keep up (and congratulations on) this well done job

**Comment by HelloMiky** [comment]
> I've downloaded the book and I've found it really useful! Keep up (and congratulations on) this well done job

It's me and I stand by my take, you did a very good job and I'm sorry if I bothered you **this morning** when I came to greet you! **You all did really well** enjoy your Sunday and have a great week

**Pull request merged**
